### ISSUE TITLE
python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc     raise KeyError(key) from err

### ISSUE THREAD

**Issue by fishfree** [negar-mokhberian/Moral_Foundation_FrameAxis#5]
When I run `python3 main.py --input_file lianghui2022.csv --docs_colname text --dict_type mfd --word_embedding_model GoogleNews-vectors-negative300.txt --output_file lianghui2022results.csv`, it showed error as below:
```
Running FrameAxis Moral Foundations scores
authority
legalisation not recognized in word embedding model
legalise not recognized in word embedding model
number of virtues:  97
number of vices:  61
(300,)
fairness
equalise not recognized in word embedding model
equaliser not recognized in word embedding model
justifie not recognized in word embedding model
injustic not recognized in word embedding model
unjustifi not recognized in word embedding model
number of virtues:  35
number of vices:  37
(300,)
general_morality
moraless not recognized in word embedding model
worthington not recognized in word embedding model
wrongdo not recognized in word embedding model
wronghead not recognized in word embedding model
number of virtues:  51
number of vices:  23
(300,)
harm
defence not recognized in word embedding model
peacemak not recognized in word embedding model
number of virtues:  55
number of vices:  74
(300,)
ingroup
allyn not recognized in word embedding model
communiti not recognized in word embedding model
enemi not recognized in word embedding model
defence not recognized in word embedding model
peacemak not recognized in word embedding model
number of virtues:  55
number of vices:  74
(300,)
ingroup
allyn not recognized in word embedding model
communiti not recognized in word embedding model
enemi not recognized in word embedding model
terrorise not recognized in word embedding model
number of virtues:  57
number of vices:  27
(300,)
purity
churchgo not recognized in word embedding model
laxalt not recognized in word embedding model
number of virtues:  62
number of vices:  71
(300,)
axes names:  ['authority', 'fairness', 'general_morality', 'harm', 'ingroup', 'purity']
Traceback (most recent call last):
  File "/home/zwz/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    mf_scores = fa.get_fa_scores(df=data, doc_colname=DOCS_COL, tfidf=False, format="virtue_vice",
  File "/home/zwz/Moral_Foundation_FrameAxis-main/frameAxis.py", line 278, in get_fa_scores
    docs = df[doc_colname]
  File "/home/zwz/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/zwz/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'text'

```
But the CSV file does have a column named 'text', which is the content I want to analyze:
![image](https://user-images.githubusercontent.com/1741341/166125391-261f17a5-14cf-454e-aaee-df1bb0cc5caf.png)

**Comment by katkasian** [comment]
I had the same issue. Yet to figure out why, but it did not appear when I had more than one column in the input file.

**Comment by katkasian** [comment]
This seems to happen because a carriage return is added to the last column name, and a file with only one column would automatically have it added.
